//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneA.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneA.Lang.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New nationality.
        /// </summary>
        public static string AddNewNationality {
            get {
                return ResourceManager.GetString("AddNewNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App color theme.
        /// </summary>
        public static string AppColorTheme {
            get {
                return ResourceManager.GetString("AppColorTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply filters.
        /// </summary>
        public static string ApplyFilters {
            get {
                return ResourceManager.GetString("ApplyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baptism.
        /// </summary>
        public static string Baptism {
            get {
                return ResourceManager.GetString("Baptism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth and death.
        /// </summary>
        public static string BirthDeathDateInterval {
            get {
                return ResourceManager.GetString("BirthDeathDateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create or edit.
        /// </summary>
        public static string CreateOrEdit {
            get {
                return ResourceManager.GetString("CreateOrEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search or create.
        /// </summary>
        public static string CreateOrSearchNationality {
            get {
                return ResourceManager.GetString("CreateOrSearchNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death date.
        /// </summary>
        public static string DeathDate {
            get {
                return ResourceManager.GetString("DeathDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected.
        /// </summary>
        public static string DeleteSelected {
            get {
                return ResourceManager.GetString("DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father.
        /// </summary>
        public static string Father {
            get {
                return ResourceManager.GetString("Father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill:\n&quot;{Country} {Acronym}&quot;.
        /// </summary>
        public static string FlyoutNationalityHelp {
            get {
                return ResourceManager.GetString("FlyoutNationalityHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has children.
        /// </summary>
        public static string HasChildren {
            get {
                return ResourceManager.GetString("HasChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont has children.
        /// </summary>
        public static string HasNotChildren {
            get {
                return ResourceManager.GetString("HasNotChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont has parents.
        /// </summary>
        public static string HasNotParents {
            get {
                return ResourceManager.GetString("HasNotParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont has spouse.
        /// </summary>
        public static string HasNotSpouse {
            get {
                return ResourceManager.GetString("HasNotSpouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has parents.
        /// </summary>
        public static string HasParents {
            get {
                return ResourceManager.GetString("HasParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has spouse.
        /// </summary>
        public static string HasSpouse {
            get {
                return ResourceManager.GetString("HasSpouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother.
        /// </summary>
        public static string Mother {
            get {
                return ResourceManager.GetString("Mother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action can&apos;t be undone, are you sure you want to continue?.
        /// </summary>
        public static string MSGconfirm {
            get {
                return ResourceManager.GetString("MSGconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing alert.
        /// </summary>
        public static string MSGconfirmTitle {
            get {
                return ResourceManager.GetString("MSGconfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved with success.
        /// </summary>
        public static string MSGSavedSuccess {
            get {
                return ResourceManager.GetString("MSGSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations.
        /// </summary>
        public static string Observations {
            get {
                return ResourceManager.GetString("Observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offsprings.
        /// </summary>
        public static string Offsprings {
            get {
                return ResourceManager.GetString("Offsprings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People list.
        /// </summary>
        public static string PeopleList {
            get {
                return ResourceManager.GetString("PeopleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset filters.
        /// </summary>
        public static string ResetFilters {
            get {
                return ResourceManager.GetString("ResetFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search here the name.
        /// </summary>
        public static string SearchTheName {
            get {
                return ResourceManager.GetString("SearchTheName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select nationality.
        /// </summary>
        public static string SelectNationality {
            get {
                return ResourceManager.GetString("SelectNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select offsprings.
        /// </summary>
        public static string SelectOffsprings {
            get {
                return ResourceManager.GetString("SelectOffsprings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select spouses.
        /// </summary>
        public static string SelectSpouses {
            get {
                return ResourceManager.GetString("SelectSpouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spouse.
        /// </summary>
        public static string Spouse {
            get {
                return ResourceManager.GetString("Spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding date.
        /// </summary>
        public static string Wedding {
            get {
                return ResourceManager.GetString("Wedding", resourceCulture);
            }
        }
    }
}
